# Etapa 1: Construcción de la aplicación
FROM node:22.9.0-alpine AS build

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el package.json y package-lock.json para instalar las dependencias
COPY package.json package-lock.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar todo el código fuente del proyecto al contenedor
COPY . .

# Construir la aplicación de React
RUN npm run build

# Etapa 2: Servir la aplicación con Nginx
FROM nginx:alpine

# Copiar los archivos construidos en la etapa anterior al directorio donde nginx los servirá
COPY --from=build /app/build /usr/share/nginx/html

# Exponer el puerto 80 para que la aplicación sea accesible
EXPOSE 80

# Iniciar nginx para servir la aplicación
CMD ["nginx", "-g", "daemon off;"]
